### ISSUE TITLE
I tried to use the Mangler in my video and it wouldn't mangle

### ISSUE THREAD

**Issue by DaileySews** [cfcurtis/pdfstitcher#173]
## Steps to reproduce the problem

1. Try to "create mangled PDF" to show how reporting a bug works
2. Get a "not responding" message
3. Wait it out
4. Get error message that PDF Mangler failed 

## Program Output
```
```

## Current Configuration
```
general:
  check_updates: true
  language: null
  margin: '0'
  open_dir: ''
  save_dir: ''
  units: !units 'INCHES'
line_props:
  colour:
    enable: true
    fill: false
    value: !!python/tuple
    - 0
    - 0
    - 0
  style:
    enable: true
    value: 0
  thickness:
    enable: true
    units: !units 'POINTS'
    value: '4'
```

## System Info
```
architecture: AMD64
pdfstitcher-version: '0.8'
platform: Windows
platform-release: '10'
platform-version: 10.0.19044
processor: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
python-build: !!python/tuple
- tags/v3.8.10:3d8993a
- May  3 2021 11:48:03
python-implementation: CPython
python-version: 3.8.10
ram: 32 GB
```
