### ISSUE TITLE
It worked!

### ISSUE THREAD

**Issue by DaileySews** [cfcurtis/pdfstitcher#175]
It worked but I forgot to reduce the pages so you have super weird instruction pages, too!

## Steps to reproduce the problem

1. testing
2. testing
3. 1 2 3

## Program Output
```
Opening E:\Dailey Sews Google Drive\Kids\Walk the Plank Kids Unisex US Letter.pdf
PDF file loaded without errors.
Warning: this PDF is encrypted with the following permissions:
accessibility: True
extract: False
modify_annotation: True
modify_assembly: False
modify_form: True
modify_other: False
print_lowres: True
print_highres: True
Please be respectful of the author and only use this tool for personal use.
File will be written to E:\Dailey Sews Google Drive\Kids\test for pdf stitcher bug reporting.pdf
Failed writing stream to page with error type <class 'TypeError'>
Tiling with 5 rows and 6 columns
Options:
    Margins: 0.0 in
    Trim: [0, 0, 0, 0] in
    Rotation: None
    Page order: Rows then columns, Left to right, Top to bottom
    Vertical alignment: Bottom
    Horizontal alignment: Left
Output size: 51.00 x 55.00 in
Tiling successful
Successfully written to E:\Dailey Sews Google Drive\Kids\test for pdf stitcher bug reporting.pdf
```

## Current Configuration
```
general:
  check_updates: true
  language: null
  margin: '0'
  open_dir: E:\Dailey Sews Google Drive\Kids
  save_dir: E:\Dailey Sews Google Drive\Kids
  units: !units 'INCHES'
line_props:
  colour:
    enable: true
    fill: false
    value: !!python/tuple
    - 0
    - 0
    - 0
  style:
    enable: true
    value: 0
  thickness:
    enable: true
    units: !units 'POINTS'
    value: '4'
```

## System Info
```
architecture: AMD64
pdfstitcher-version: '0.8'
platform: Windows
platform-release: '10'
platform-version: 10.0.19044
processor: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
python-build: !!python/tuple
- tags/v3.8.10:3d8993a
- May  3 2021 11:48:03
python-implementation: CPython
python-version: 3.8.10
ram: 32 GB
```

[e97b7a15f2b6bdd664633f2d5a3bc9a4.pdf](https://github.com/cfcurtis/pdfstitcher/files/10844861/e97b7a15f2b6bdd664633f2d5a3bc9a4.pdf)
