### ISSUE TITLE
Still failing to mangle

### ISSUE THREAD

**Issue by DaileySews** [cfcurtis/pdfstitcher#176]
## Steps to reproduce the problem

1. delete the program that was working 
2. download the 0.8.1 version from the website for video purposes
3. attempt to mangle PDF
4. no option of where to save
5. "failed to mangle" pop up
6. can be resolved by downloading "old" version from Facebook messenger chat
7. complete video as if nothing went wrong
8. send message and report to poor Charlotte who is probably tired of these messages by now...sorry 

## Program Output
```
Opening E:\Dailey Sews Google Drive\Kids\Walk the Plank Kids Unisex US Letter.pdf
PDF file loaded without errors.
Warning: this PDF is encrypted with the following permissions:
accessibility: True
extract: False
modify_annotation: True
modify_assembly: False
modify_form: True
modify_other: False
print_lowres: True
print_highres: True
Please be respectful of the author and only use this tool for personal use.
File will be written to C:\Users\phili\OneDrive\Desktop\test for bug report.pdf
Tiling with 4 rows and 6 columns
Options:
    Margins: 0.0 in
    Trim: [0, 0.5, 0, 0.5] in
    Rotation: None
    Page order: Rows then columns, Left to right, Top to bottom
    Vertical alignment: Bottom
    Horizontal alignment: Left
Output size: 48.00 x 42.00 in
Tiling successful
Successfully written to C:\Users\phili\OneDrive\Desktop\test for bug report.pdf
```

## Current Configuration
```
general:
  check_updates: true
  language: null
  margin: '0'
  open_dir: E:\Dailey Sews Google Drive\Kids
  save_dir: C:\Users\phili\OneDrive\Desktop
  units: !units 'INCHES'
line_props:
  colour:
    enable: true
    fill: false
    value: !!python/tuple
    - 0
    - 0
    - 0
  style:
    enable: true
    value: 0
  thickness:
    enable: true
    units: !units 'POINTS'
    value: '4'
```

## System Info
```
architecture: AMD64
pdfstitcher-version: '0.8'
platform: Windows
platform-release: '10'
platform-version: 10.0.19044
processor: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
python-build: !!python/tuple
- tags/v3.8.10:3d8993a
- May  3 2021 11:48:03
python-implementation: CPython
python-version: 3.8.10
ram: 32 GB
```
