### ISSUE TITLE
pattern lines disappear after using pdf stitcher 

### ISSUE THREAD

**Issue by squikler** [cfcurtis/pdfstitcher#186]
I'm trying to change the line thickness to 4pt and BRIGHT GREEN, which i've done a million time without issue in PDF Stitcher, but for whatever reason, on this file, it shows it writes successfully but adobe says there's an error and doesn't show any pattern lines at all, just the titles and grid. even if all sizes are selected, i just dont get it.  (I've managed to make it work as downloaded but still cannot get it to work with pdf stitcher even the newest version)

## Steps to reproduce the problem

1. open girls boyfriend cardigan projector pattern, 
2. deselect all layers except 6
3. chnge line color to green 4 pt thick, solid
4. apply to checked layers
5. select titles box
6. generate pdf 

## Program Output
```
Opening C:\Users\jessw\Downloads\Girls-Boyfriend-Cardigan-projector-file.pdf
PDF file loaded without errors.
Please be respectful of the author and only use this tool for personal use.
File will be written to C:\Users\jessw\Downloads\bf.pdf
Successfully written to C:\Users\jessw\Downloads\bf.pdf
```

## Current Configuration
```
general:
  check_updates: true
  language: en
  margin: '0'
  open_dir: C:\Users\jessw\Downloads
  save_dir: C:\Users\jessw\Downloads
  units: !units 'INCHES'
line_props:
  colour:
    enable: true
    fill: false
    value: !!python/tuple
    - 0
    - 0
    - 0
  style:
    enable: true
    value: 0
  thickness:
    enable: true
    units: !units 'POINTS'
    value: '4'
```

## System Info
```
architecture: AMD64
pdfstitcher-version: 0.8.5
platform: Windows
platform-release: '10'
platform-version: 10.0.19045
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
python-build: !!python/tuple
- tags/v3.8.10:3d8993a
- May  3 2021 11:48:03
python-implementation: CPython
python-version: 3.8.10
ram: 16 GB
```

[5bdd086a6234cee8b33412d515af867b.pdf](https://github.com/cfcurtis/pdfstitcher/files/11363549/5bdd086a6234cee8b33412d515af867b.pdf)
![image](https://user-images.githubusercontent.
![344766965_1289182055043221_8534251904304313716_n](https://user-images.githubusercontent.com/132246998/235408016-e1d43dc3-ab67-4a9b-a95a-e3b9b9efe938.jpg)
![343796511_234788199227333_4170352360307895027_n](https://user-images.githubusercontent.com/132246998/235408019-097668ef-d5cc-4988-af80-9c853f5a8422.jpg)
![344551655_793646072285345_2798847356078369426_n](https://user-images.githubusercontent.com/132246998/235408020-412d8182-1fdf-4d17-a38f-837b34621ec7.jpg)
com/132246998/235407848-4f96ceaf-17d7-4542-bd3b-35f2c69ffbac.png)
